function(filter_cxx_flags flags)
    include(CheckCXXCompilerFlag)
    set(output_flags)
    foreach(FLAG IN ITEMS ${${flags}})
        string(REPLACE "=" "-" FLAG_VAR "${FLAG}")
        if(NOT DEFINED IS_SUPPORTED_${FLAG_VAR})
            check_cxx_compiler_flag("${FLAG}" IS_SUPPORTED_${FLAG_VAR})
        endif()
        if(IS_SUPPORTED_${FLAG_VAR})
            list(APPEND output_flags $<$<COMPILE_LANGUAGE:CXX>:${FLAG}>)
        endif()
    endforeach()
    set(${flags} ${output_flags} PARENT_SCOPE)
endfunction()

function(filter_linker_flags flags)
    include(CheckLinkerFlag)
    set(output_flags)
    foreach(FLAG IN ITEMS ${${flags}})
        string(REPLACE "=" "-" FLAG_VAR "${FLAG}")
        if(NOT DEFINED IS_SUPPORTED_${FLAG_VAR})
            check_linker_flag(CXX "${FLAG}" IS_SUPPORTED_${FLAG_VAR})
        endif()
        if(IS_SUPPORTED_${FLAG_VAR})
            list(APPEND output_flags $<$<COMPILE_LANGUAGE:CXX>:${FLAG}>)
        endif()
    endforeach()
    set(${flags} ${output_flags} PARENT_SCOPE)
endfunction()
